### ISSUE TITLE
AspectFit and Aspect Fill mode don't work properly when using Zoomy intazoom mode

### ISSUE THREAD

**Issue by bizibizi** [lvnkmn/Zoomy#62]
It;s crashing all UI basically. Can you check it please?

**Comment by bizibizi** [comment]
i am using those methids as well

extension YourViewController: Zoomy.Delegate {
    
    func didBeginPresentingOverlay(for imageView: UIImageView) {
        scrollView.isScrollEnabled = false
    }
    
    func didEndPresentingOverlay(for imageView: UIImageView) {
        scrollView.isScrollEnabled = true
    }
}

**Comment by bizibizi** [comment]
well, i solved that with https://github.com/ergunemr/EEZoomableImageView

**Comment by mennolovink** [comment]
Glad you have been able to fix this in your code. This is a known issue indeed. Currently Zoomy doesn't have full support for all content modes and works best when the aspect ratio of the image and the aspect ratio of the image view it's displayed in stay the same.

**Comment by lvnkmn** [comment]
@bizibizi I've found some time and will pick this issue up. Since I see you have been dealing with this in the insta zoom mode, I will first solve it in this mode (and later for the scroll based mode in #67)
