### ISSUE TITLE
UICollectionView Zoom Bug

### ISSUE THREAD

**Issue by wy353208214** [lvnkmn/Zoomy#79]
When i use the method `UICollectionView.scrollToItem()` to scroll a position,  after it i scroll the collection by my self.
And now i zoom the image, The UICollection will autoscroll to the position which the `UICollectionView.scrollToItem()` is scrolled.

![1](https://user-images.githubusercontent.com/3038374/128688587-76743f3d-8819-48af-9c6d-66f88465a146.gif)

**Comment by lvnkmn** [comment]
I see, thanks for letting me know. I’ll have a look into this.

what is your expected behavior?

**Comment by wy353208214** [comment]
> I see, thanks for letting me know. I’ll have a look into this.
> 
> what is your expected behavior?

Thank you!
It's possible not a bug, because i  use `scrollToItem` in `viewDidLayoutSubviews` for UIViewController. And now i move `scrollToItem` in `viewDidLoad`, it's worked.
