### ISSUE TITLE
An approach for disabling other gesture when using zoom behavior in complicated hierarchy.

### ISSUE THREAD

**Issue by kanottonp** [lvnkmn/Zoomy#81]
Hi guys, hope you're good there.

First of all, I just found this library today and I'm appreciated it so much. Thank you for doing this. I think you're a savior for many guy out there.

As I applied it to my work, There were many ImageViews inside many parent views, some were TableViewCell, some were CollectionViewCell, and some were CollectionViewCell inside CollectionView inside TableViewCell in Tableview.

It didn't take too much effort to `addZoomBehavior(for: Zoomable)`, I've done it by recurring new UIResponder to find the closest ViewController for adding it. But there was an issue about how to disable scrollView from CollectionView and TableView at the same time. The approach showed in README would't work for this.

So I have to change something in `ImageZoomController.swift` about `UIGestureRecognizerDelegate`  to choose the gesture that can be done in a time, likes below, and it works for my case.

```
extension ImageZoomController: UIGestureRecognizerDelegate {
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer == imageViewPinchGestureRecognizer,
            gestureRecognizer.numberOfTouches > 1,
            otherGestureRecognizer is UIPanGestureRecognizer &&
            otherGestureRecognizer != imageViewPanGestureRecognizer {
            return false
        }
        return true
    }
    
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldBeRequiredToFailBy otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer == imageViewPinchGestureRecognizer,
            gestureRecognizer.numberOfTouches > 1,
            otherGestureRecognizer is UIPanGestureRecognizer &&
            otherGestureRecognizer != imageViewPanGestureRecognizer {
            return true
        }
        return false
    }
    
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        guard let action = gestureRecognizerActions[gestureRecognizer] else { return true }
        
        return !(action is Action.None)
    }
}
```

So I compose this issue for asking for your suggestion if there is a better way to make it. 

In my opinion, It might be great if there is an implementation for making a delegate for ` UIGestureRecognizerDelegate` for one who need zoom behavior to work for some situations or to not work for some situations too.

Thank you in advance!

PS. If you like this approach or want me to adjust a few code. I would love to contribute the library as I have attached a pull request below.

**Comment by lvnkmn** [comment]
Hi,

Thanks for the kind words. Also thanks for your PR. I have merged it and will create a new release as soon as I have time, when it's released I will close this issue.

Kind regards,
Menno
