### ISSUE TITLE
very interesting, but if I zoom image don't update.

### ISSUE THREAD

**Issue by PaolinoAngeletti** [lvnkmn/Zoomy#83]
i have an image view that update every second.
the problem is that if I zoom the image, the content isnt updated untill zoom released

**Comment by lvnkmn** [comment]
Hi Paulino,

Glad you find Zoomy interesting 🙂

Zoomy works by creating a bunch of new UIImageViews which are overlayed on top of your original UIImageView, sometimes in a UIScrollView, sometimes as a floating imageView (usually during transitions). The state of the original UIImageView is only reflected when the zooming starts, so yes: what you're describing is totally not implemented right now.

While with some proper coding fu, it should probably not be impossible to do what you're trying to achieve (by contributing to this library), I'd have to warn anyone who's trying to do this. The biggest pain you will encounter will have to do with the fact that the changing images will most likely have different aspect ratios which means you have to properly re calculate how the overlaying imageviews will still match the original one without animation glitches. This was actually already the hardest part of creating Zoomy.

That being said, feel free to have a shot at it and send me a pull request, I will not attempt this myself as it will be too much work aside from my regular job.

I will close this issue, feel free to reopen If you (or anyone is) would like to work on it.

Cheers,
Menno
